#!/usr/bin/env node
// Writes docs/CREDITS.md from scripts/image-sources.json (run after
// changing a photo): every photo with its photographer, source and license,
// plus the fonts and icons.
//
//   node scripts/credits.mjs

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const sources = JSON.parse(await readFile(join(ROOT, 'scripts', 'image-sources.json'), 'utf8'));

const site = (url) => (url.includes('pexels.com') ? 'Pexels' : 'Unsplash');
const rows = sources.map((s) => {
  const who = s.photographer ? (s.photographerUrl ? `[${s.photographer}](${s.photographerUrl})` : s.photographer) : 'Unknown';
  return `| \`${s.id}\` | ${who} | [${site(s.pageUrl)}](${s.pageUrl}) | ${s.license} |`;
});

const md = `# Credits

## Photography

Every photo is free to use under its site's license, downloaded (never hotlinked) and served as AVIF and WebP at several sizes (\`npm run images\`, from \`scripts/image-sources.json\`, which also describes each one). Thank you to the photographers.

| Photo | Photographer | Source | License |
|---|---|---|---|
${rows.join('\n')}

## Fonts

Self-hosted from the [Fontsource](https://fontsource.org) builds, all under the [SIL Open Font License 1.1](https://openfontlicense.org):

- **Sora** by Jonathan Barnbrook and Julián Moncada: variable, Latin subset (headings, stats, buttons)
- **Inter** by Rasmus Andersson: variable, Latin subset (body text)
- **Readex Pro** by Thomas Jockin, Nadine Chahine and Bonnie Shaver-Troup: variable, Arabic subset (Arabic headings)
- **IBM Plex Sans Arabic** by Mike Abbink and Bold Monday for IBM: 400 and 600, Arabic subset (Arabic body text)

Code uses the system's monospace font.

## Software that runs in your browser (loaded only when an exercise needs it)

- [CodeMirror 6](https://codemirror.net) (MIT) — the exercise editor
- [Sucrase](https://github.com/alangpierce/sucrase) (MIT) — compiles JSX in the playground
- [TypeScript](https://www.typescriptlang.org) (Apache-2.0) — type-checks TypeScript exercises
- [sql.js](https://sql.js.org) (MIT), SQLite compiled to WebAssembly — runs the SQL exercises
- [Pyodide](https://pyodide.org) (MPL-2.0), CPython for WebAssembly with pandas, NumPy and scikit-learn — runs the Python exercises; loaded from its CDN on first use and cached offline
- [React](https://react.dev) (MIT) — also rendered inside the playground for React exercises

Syntax highlighting is done at build time with [Shiki](https://shiki.style) (MIT) using GitHub's light and dark default themes.

## Icons

[Lucide](https://lucide.dev) (ISC License). The GitHub mark in the developer credit is GitHub's.

## Content and data

All 303 lessons, quizzes, exercises, glossaries and catalog copy (in English and Arabic) were written for this project; instructors, reviewers and testimonial authors are fictional. "Cartwheel", the sample store used by the SQL and Python courses, is generated by \`scripts/content/make-dataset.mjs\`. scikit-learn's bundled datasets (Iris, Wine, Breast Cancer Wisconsin, Diabetes, Digits) are used in the Machine Learning course under their original licenses.
`;
await writeFile(join(ROOT, 'docs', 'CREDITS.md'), md);
console.log(`docs/CREDITS.md: ${sources.length} photos`);
